# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilder < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/punkwalker/idpbuilder/releases/download/v0.0.1/idpbuilder-darwin-amd64.tar.gz"
      sha256 "9abae30a259ac28d7ff76d7dfff32d951ca88b6cd9e9cb9ceec91719caffdd28"

      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/punkwalker/idpbuilder/releases/download/v0.0.1/idpbuilder-darwin-arm64.tar.gz"
      sha256 "dcedc9fb34f598124a5115a1e086576567bfe596ec40f73429308b121a34d2ed"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/punkwalker/idpbuilder/releases/download/v0.0.1/idpbuilder-linux-amd64.tar.gz"
      sha256 "094153d8cadf2d13016d61bb5b2d32304837e641ad82aa3d37ce7e67a1fefc32"
      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/punkwalker/idpbuilder/releases/download/v0.0.1/idpbuilder-linux-arm64.tar.gz"
      sha256 "3d5e9f495b8191ec280acf62b37da8a9e83a95e71c2febd643de88f773b18ca5"
      def install
        bin.install "idpbuilder"
      end
    end
  end

  test do
    system "#{bin}/idpbuilder --version"
  end
end
