# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KarpenterGenerate < Formula
  desc "A simple CLI tool to generate Karpenter CRDs from EKS Managed Node Groups"
  homepage "https://github.com/punkwalker/karpenter-generate"
  version "0.0.3"
  license "MIT-0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.3/karpenter-generate_Darwin_x86_64.tar.gz"
      sha256 "c0876eaf3a524e632fb03f6ee1522ca4a6dd8b6647d13bc826721f6442679633"

      def install
        bin.install "karpenter-generate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.3/karpenter-generate_Darwin_arm64.tar.gz"
      sha256 "096a07802857c3bc2a06b80c8c3aa1d04e9558b5ba094d9cbef00c22e8fe560e"

      def install
        bin.install "karpenter-generate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.3/karpenter-generate_Linux_x86_64.tar.gz"
      sha256 "49ed94a8ad184f64c043001cbb4a95d285a90ec3517a2480fcfc46a07c1a6579"

      def install
        bin.install "karpenter-generate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.3/karpenter-generate_Linux_arm64.tar.gz"
      sha256 "f01382609aca4540f2e139e64512232f5658acc50975fa18cf6ad07a85120ff3"

      def install
        bin.install "karpenter-generate"
      end
    end
  end
end
