# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KarpenterGenerate < Formula
  desc "A simple CLI tool to generate Karpenter CRDs from EKS Managed Node Groups"
  homepage "https://github.com/punkwalker/karpenter-generate"
  version "0.0.4"
  license "MIT-0"

  on_macos do
    on_intel do
      url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.4/karpenter-generate_Darwin_x86_64.tar.gz"
      sha256 "d925084b9843812e0a63c21804bb8f11317582188599bc103238ebc3a8d38847"

      def install
        bin.install "karpenter-generate"
      end
    end
    on_arm do
      url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.4/karpenter-generate_Darwin_arm64.tar.gz"
      sha256 "0ed13ebc0dee686b8171740a1c56766caddec89b649292827397b2580de19913"

      def install
        bin.install "karpenter-generate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.4/karpenter-generate_Linux_x86_64.tar.gz"
        sha256 "5b970e8e60ccec5f7876fe9e7024f84e2908a532a253368ffa7e75cb701dae9a"

        def install
          bin.install "karpenter-generate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/punkwalker/karpenter-generate/releases/download/v0.0.4/karpenter-generate_Linux_arm64.tar.gz"
        sha256 "e5311085a60ebaf7a8fe87affe5d682ddab2010824c226b0e64b54e51f1eaf81"

        def install
          bin.install "karpenter-generate"
        end
      end
    end
  end
end
